cas: Disable PRODUCT_OTA_ENFORCE_VINTF_KERNEL_REQUIREMENTS Adding those configs in defconfig did not fix these errors:
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
    Missing config CONFIG_HAVE_MOVE_PMD
    Missing config CONFIG_HAVE_MOVE_PUD
    Missing config CONFIG_USERFAULTFD

They kept coming, so I used this flag in the DT:
PRODUCT_OTA_ENFORCE_VINTF_KERNEL_REQUIREMENTS := false