cas: Drop android.hardware.bluetooth.audio and android.hardware.health
ERROR: files are incompatible: android.hardware.bluetooth.audio@2.2::IBluetoothAudioProvidersFactory/default is deprecated in compatibility matrix at FCM Version 7; it should not be served.
    because it matches android.hardware.bluetooth.audio@2.0::IBluetoothAudioProvidersFactory/default from /system/etc/vintf/compatibility_matrix.6.xml
android.hardware.health@2.1::IHealth/default is deprecated in compatibility matrix at FCM Version 7; it should not be served.
    because it matches android.hardware.health@2.1::IHealth/default from /system/etc/vintf/compatibility_matrix.6.xml: Success
INCOMPATIBLE

ERROR: files are incompatible: android.hardware.bluetooth.audio@2.1::IBluetoothAudioProvidersFactory/default is deprecated in compatibility matrix at FCM Version 7; it should not be served.
    because it matches android.hardware.bluetooth.audio@2.0::IBluetoothAudioProvidersFactory/default from /system/etc/vintf/compatibility_matrix.6.xml
android.hardware.health@2.1::IHealth/default is deprecated in compatibility matrix at FCM Version 7; it should not be served.
    because it matches android.hardware.health@2.1::IHealth/default from /system/etc/vintf/compatibility_matrix.6.xml
The following instances are in the device manifest but not specified in framework compatibility matrix:
    android.hardware.health@2.1::IHealth/default
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 7.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 7 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.
5. For `android.*` HALs that are using unexpected instance names, the instance names need to be added to the AOSP framework compatibility matrices. A regex wildcard can be used if the instance names are proprietary.
: Success